# Imagen base
FROM node:20-alpine

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y lock para instalar deps primero (mejor caché)
COPY package*.json ./

# Instalar dependencias
RUN npm install --production

# Copiar el resto del backend
COPY . .

# Puerto del backend (tu server usa 3000)
EXPOSE 3000

# Ejecutar servidor
CMD ["node", "server.js"]
