# 1) Build
FROM node:20-alpine AS build
WORKDIR /app

# Copiamos solo el frontend
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./

# Build de Vite (ya NO dependemos de VITE_API_URL para Kubernetes)
RUN npm run build


# 2) Servir estático con nginx + proxy /api -> backend
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Copia la config de nginx con el proxy
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
